### ISSUE TITLE
Readme 修改建议

### ISSUE THREAD

**Issue by Chengzi600** [SpaceXC/Re-WearBili#4]
_“在Android Studio中删除位于cn.spacexc.wearbili.remake.app.splash.ui.SplashScreen.kt中有关更新检测以及内测资格检查的相关代码”_

这句话里面的文件名应该是SplashScreenActivity.kt

虽然熟练安卓开发的一眼能看出来不对劲

但对于我这种没怎么接触过安卓开发的，又因为没内测资格不得不自己构建的（    容易造成误解

如果你们开发确实是这样表述的那就close掉这个issue吧

**Comment by Chengzi600** [comment]
ww

**Comment by SpaceXC** [comment]
> _“在Android Studio中删除位于cn.spacexc.wearbili.remake.app.splash.ui.SplashScreen.kt中有关更新检测以及内测资格检查的相关代码”_
> 
> 
> 
> 这句话里面的文件名应该是SplashScreenActivity.kt
> 
> 
> 
> 虽然熟练安卓开发的一眼能看出来不对劲
> 
> 
> 
> 但对于我这种没怎么接触过安卓开发的，又因为没内测资格不得不自己构建的（    容易造成误解
> 
> 
> 
> 如果你们开发确实是这样表述的那就close掉这个issue吧
> 
> 

这是一个历史遗留问题啦，我写Readme的时候的文件名确实是那个，因为那是用的是navigation，所以没有activity

后来发现navgiation在国内手表上表现很差就换回activity了

感谢指正XD
